### ISSUE TITLE
Feature Request: Support multi-stage docker builds

### ISSUE THREAD

**Issue by lizardruss** [covexo/devspace#252]
In my current project, we use a `development` build stage and a leaner `production` build stage to produce an image for local development and one to deploy.

I haven't found an option to specify a build target to use for for a multi-stage build. It would be great if this option could be added.

Thanks for the awesome tool!

**Comment by FabianK1991** [comment]
Thanks for creating this issue! Yes we should definitely add that. We'll add the target option to the "images[].build" section in the .devspace/config file. Actually we also should improve the config for this section, because currently it is already possible to specify buildArgs, contextPath and dockerfilePath for building the image, but this functionality is not documented yet.

I will work on this today and we'll ship it with release 1.1.0, which should come out either today or tomorrow.

**Comment by FabianK1991** [comment]
Should be fixed in v1.1.0
