### ISSUE TITLE
Persistance volume in main pod

### ISSUE THREAD

**Issue by irfani** [covexo/devspace#442]
**Is your feature request related to a problem?**
we often face the problem when pod needs persistance volume. For example to prevent redownload gradle/maven repo

**Which solution do you suggest?**  
add additional config in config.yaml/deployment.yaml to enable persistance volume.

/kind feature

**Comment by FabianKramm** [comment]
Thanks for opening this issue. I'm not 100% sure if I understood your problem correctly, because you can always add the persistent volume that you need to the deployment.yaml yourself, since it is a standard kubernetes deployment yaml file. Also the sync should work the same with persistent volumes as with ephemeral storage.

**Comment by LukasGentele** [comment]
Closing this for now. Please re-open if the issue has not been resolved.
